#!/usr/bin/env bash

if [ -z "$VERSION" ]; then
    VERSION=$(node -e "console.log(require('./package.json').version)")
fi

if [ -z "$NAME" ]; then
    NAME=$(node -e "console.log(require('./package.json').name.split('/').pop())")
fi

PREFIX=$(node -e "console.log(require('./package.json')['docker-registry'] || '')")
if [ -z "$PREFIX" ]; then
    PREFIX=$(node -e "console.log(require('./package.json')['docker-user'] || '')")
fi

if [ -z "$PREFIX" ]; then
    echo "docker push requires either docker-registry or docker-user in package.json"
    exit 1
fi

echo "$VERSION"

# Argumentos
TAG="latest"
if [ "$#" -ne 0 ]; then
	ARG=$(echo "$@" | cut -d "=" -f 1)
	VALOR=$(echo "$@" | cut -d "=" -f 2)
	echo "$ARG = $VALOR"    
	
    if test "$ARG" = "env"; then
        TAG="$VALOR"

        docker tag "$NAME:$VERSION" "$PREFIX/$NAME:$TAG-$VERSION"
        docker push "$PREFIX/$NAME:$TAG-$VERSION"
    fi
fi

docker tag "$NAME:$VERSION" "$PREFIX/$NAME:$TAG"
docker push "$PREFIX/$NAME:$TAG"
